### ISSUE TITLE
attempts to add MISP exports into MISP via python

### ISSUE THREAD

**Issue by maisenhe** [CIRCL/PyMISP#112] opened 2017-07-19 18:12 UTC
I use the following code to upload either of the attached files and I end up with an empty event in MISP.

MISP
Currently installed version..... v2.4.77 (272d8930944c9e57812e256e4dd72136fef3fd7a)

`import json
from pymisp import PyMISP
from pprint import pprint
misp_url = "http://<redacted>"
misp_key = "<redacted"
def init(url, key):
  return PyMISP(url, key, 'misp')
misp = init(misp_url, misp_key)

#with open('MISP-test-files/vx-misp.xml', 'r') as f:
with open('MISP-test-files/vx-json.json', 'r') as f:
    data = json.load(f)
test = misp.add_event(data)

#print(test)
print(json.dumps(data))`

I would prefer to be able to to feed MISP XML directly to the add_event() function but it only accepts json objects. Let me know what other info you require.
[Archive.zip](https://github.com/CIRCL/PyMISP/files/1160015/Archive.zip)

**Comment by Rafiot** [comment] 2017-10-28 21:11
Duplicate of https://github.com/MISP/PyMISP/issues/97

**Closed by Rafiot** 2017-10-28 21:11 UTC
